[dependencies]
core = "2.0.0"

[dev-dependencies]
test = "2.0.0"
fuzz = "0.2.1"

[package]
name = "class-plus"
version = "0.2.0"
description = "Class Plus Helper - Initialization patterns and mixins for Motoko actors"
repository = "https://github.com/icdevsorg/class-plus"
keywords = [ "class", "motoko", "helper", "mixin", "initialization" ]

[toolchain]
moc = "1.1.0"
